version: 1.0.{build}

image: Visual Studio 2022

skip_tags: true

skip_commits:
  files:
    - '**/*.md'
    - .github/
    - data/*
    - .gitattributes
    - .gitignore
    - .travis.yml
    - README

configuration:
  - Release
platform:
  - Win32
  - x64

before_build:
  - git tag --delete nightly-build
  - git clone --depth 1 https://github.com/mupen64plus/mupen64plus-win32-deps.git ..\mupen64plus-win32-deps
  - git clone --depth 1 https://github.com/mupen64plus/mupen64plus-core.git ..\mupen64plus-core

build_script:
  - msbuild projects\msvc\mupen64plus-ui-console.vcxproj /p:Configuration=%configuration%;Platform=%platform%

after_build:
  - ps: $env:rev1 = git describe --tags
  - set rev2=%platform%
  - if "%rev2%"=="Win32" set rev2=x86
  - set filepkg=mupen64plus-ui-console_v%rev1%_%rev2%
  - md tdata
  - cd tdata
  - copy ..\projects\msvc\%platform%\%configuration%\*.exe .
  - copy ..\..\mupen64plus-core\data\* .
  - copy ..\..\mupen64plus-win32-deps\freetype-2.13.0\lib\%rev2%\*.dll .
  - copy ..\..\mupen64plus-win32-deps\libpng-1.6.39\lib\%rev2%\*.dll .
  - copy ..\..\mupen64plus-win32-deps\SDL2-2.26.3\lib\%rev2%\*.dll .
  - copy ..\..\mupen64plus-win32-deps\SDL2_net-2.2.0\lib\%rev2%\*.dll .
  - copy ..\..\mupen64plus-win32-deps\zlib-1.2.13\lib\%rev2%\*.dll .
  - 7z a -t7z ..\build\%filepkg%.7z *

artifacts:
  - path: build\$(filepkg).7z
    name: $(filepkg)
