[package]
name = "mupen64plus-input-gca"
version = "0.6.0"
authors = ["Amandus Søve Thorsrud <ama.thorsrud@gmail.com>"]
edition = "2021"
license = "MIT"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
libloading = "0.7.0"
rusb = "0.9.0"
once_cell = "1.9"
serde = { version = "1.0", features = ["derive"] }
toml = "0.5"

[features]
default = []
m64p_compat = []

[profile.release]
panic = "abort"
