name: CXD4 RSP

on:
  push:
    paths-ignore:
      - '**/*.md'
      - '.{gitattributes,gitignore,travis.yml}'
      - 'appveyor.yml,README'
  pull_request:
    paths-ignore:
      - '**/*.md'
      - '.{gitattributes,gitignore,travis.yml}'
      - 'appveyor.yml,README'
  workflow_dispatch:
jobs:

  Linux:
    strategy:
      fail-fast: false
      matrix:
        include:
          - cc: GCC
            platform: x64
            bits: 64
          - cc: GCC
            platform: x86
            bits: 32
          - cc: Clang
            platform: x64
            bits: 64
          - cc: Clang
            platform: x86
            bits: 32
    name: Linux / ${{ matrix.cc }} / ${{ matrix.platform }}
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Get build dependencies and arrange the environment
        run: |
          sudo apt-get update
          sudo apt-get --reinstall -y install gcc-multilib g++-multilib libc6 libc6-dev-i386
          sudo ldconfig
      - name: Build and related stuff
        run: |
          if [[ ${{ matrix.bits }} -eq 32 ]]; then export OPTFLAGS="-O2 -flto -mtune=pentium4"; else export OPTFLAGS="-O2 -flto -mtune=core2"; fi
          G_REV=$(git rev-parse --short HEAD)
          echo "G_REV=${G_REV}" >> "${GITHUB_ENV}"
          ORIG="$(pwd)"
          if [[ "${{ matrix.cc }}" == "GCC" ]]; then
            CC="gcc"
            CXX="g++"
          else
            CC="clang"
            CXX="clang++"
          fi
          if [[ ${{ matrix.bits }} -eq 32 ]]; then export PIC="1"; fi
          ${CC} --version
          echo ""
          git clone --depth 1 https://github.com/mupen64plus/mupen64plus-core.git ../mupen64plus-core
          mkdir tmp
          for SSE in none SSE2
          do
            echo ""
            echo ":: ${{ matrix.cc }} ${{ matrix.platform }}${MSG} ::"
            echo ""
            make SSE="${SSE}" -C projects/unix clean
            echo ""
            make CC="${CC}" CXX="${CXX}" BITS="${{ matrix.bits }}" SSE="${SSE}" -C projects/unix all -j4
            echo ""
            make SSE="${SSE}" -C projects/unix install DESTDIR="${ORIG}/tmp"
            echo ""
            cd tmp/usr/local/lib/mupen64plus
            ls -gG mupen64plus-rsp-cxd4${LIB}.so
            ldd mupen64plus-rsp-cxd4${LIB}.so
            LIB="-sse2"
            MSG=" / SSE2"
            cd "${ORIG}"
          done
          mkdir pkg
          if [[ "${CC}" == "gcc" ]]; then tar cvzf pkg/mupen64plus-rsp-cxd4-${{ matrix.platform }}-g${G_REV}.tar.gz -C tmp/ "usr"; fi
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mupen64plus-rsp-cxd4-${{ matrix.platform }}-g${{ env.G_REV }}
          path: pkg/*
          if-no-files-found: ignore

  MSYS2:
    strategy:
      fail-fast: false
      matrix:
        include:
          - cc: GCC
            platform: x64
            cross: x86_64
            bits: 64
          - cc: GCC
            platform: x86
            cross: i686
            bits: 32
    name: Windows / MSYS2 ${{ matrix.cc }} / ${{ matrix.platform }}
    runs-on: windows-2019
    defaults:
      run:
        shell: msys2 {0}
    steps:
      - uses: actions/checkout@v3
      - uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW${{ matrix.bits }}
          update: true
          install: >-
            git
            libtool
            make
            mingw-w64-${{ matrix.cross }}-gcc
            mingw-w64-${{ matrix.cross }}-toolchain
      - name: Build and related stuff
        run: |
          if [[ ${{ matrix.bits }} -eq 32 ]]; then export OPTFLAGS="-O2 -flto -mtune=pentium4"; else export OPTFLAGS="-O2 -flto -mtune=core2"; fi
          echo "G_REV=$(git rev-parse --short HEAD)" >> "${GITHUB_ENV}"
          ORIG="$(pwd)"
          CC="gcc"
          CXX="g++"
          ${CC} --version
          echo ""
          git clone --depth 1 https://github.com/mupen64plus/mupen64plus-core.git ../mupen64plus-core
          mkdir tmp
          for SSE in none SSE2
          do
            echo ""
            echo ":: ${{ matrix.cc }} ${{ matrix.platform }}${MSG} ::"
            echo ""
            make SSE="${SSE}" -C projects/unix clean
            echo ""
            make CC="${CC}" CXX="${CXX}" BITS="${{ matrix.bits }}" SSE="${SSE}" -C projects/unix all -j4
            echo ""
            make SSE="${SSE}" -C projects/unix install PLUGINDIR="" SHAREDIR="" BINDIR="" MANDIR="" LIBDIR="" APPSDIR="" ICONSDIR="icons" INCDIR="api" LDCONFIG="true" DESTDIR="${ORIG}/tmp"
            echo ""
            ls -gG tmp/mupen64plus-rsp-cxd4${LIB}.dll
            ldd tmp/mupen64plus-rsp-cxd4${LIB}.dll
            LIB="-sse2"
            MSG=" / SSE2"
          done
      - name: Copy binaries, dependencies, etc...
        run: |
          mkdir pkg
          cd tmp
          for BIN in *.dll
          do
            echo ":: Copying ${BIN}"
            cp "${BIN}" ../pkg/
          done
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mupen64plus-rsp-cxd4-msys2-${{ matrix.platform }}-g${{ env.G_REV }}
          path: pkg/*

  MSVC:
    strategy:
      fail-fast: false
      matrix:
        include:
          - toolset: v143
            platform: x64
            vs: 2022
          - toolset: v141_xp
            platform: x86
            vs: 2019
    name: Windows / MSVC ${{ matrix.toolset }} / ${{ matrix.platform }}
    runs-on: windows-${{ matrix.vs }}
    defaults:
      run:
        shell: cmd
    steps:
      - uses: actions/checkout@v3
      - uses: microsoft/setup-msbuild@v1
    #  with:
    #    vs-version: 16.11
      - name: Build and related stuff
        run: |
          for /f "tokens=1" %%R in ('git rev-parse --short HEAD') do set "G_REV=%%R"
          echo G_REV=%G_REV%>> "%GITHUB_ENV%"
          set "ARCH=${{ matrix.platform }}"
          if [%ARCH%] == [x86] set "ARCH=Win32"
          echo.
          msbuild --version
          echo.
          git clone --depth 1 https://github.com/mupen64plus/mupen64plus-core.git ..\mupen64plus-core
          echo.
          msbuild projects\msvc\mupen64plus-rsp-cxd4.vcxproj /p:Configuration=Release;Platform=%ARCH%;PlatformToolset=${{ matrix.toolset }}
          echo.
          md backup
          copy projects\msvc\%ARCH%\Release\mupen64plus-rsp-cxd4.dll backup\
          dir backup\*.dll
      - name: Copy binaries, dependencies, etc...
        run: |
          md pkg
          cd pkg
          xcopy "..\backup" .
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: mupen64plus-rsp-cxd4-msvc-${{ matrix.platform }}-g${{ env.G_REV }}
          path: pkg/*

  Nightly-build:
    runs-on: ubuntu-latest
    needs: [Linux, MSYS2, MSVC]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v3
      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: binaries
      - name: Get some tools
        run: |
          sudo apt-get update
          sudo apt-get -y install hashdeep
      - name: Creating new artifacts and update nightly-build
        run: |
          mkdir pkg
          cd binaries
          for BIN in *
          do
            cd "${BIN}"
            if [[ "${BIN:21:4}" == "msys" ]]; then
              echo ":: Creating ${BIN}.zip"
              zip -r "../../pkg/${BIN}.zip" *
            elif [[ "${BIN:21:4}" == "msvc" ]]; then
              echo ":: Creating ${BIN}.zip"
              zip -r "../../pkg/${BIN}.zip" *
            else
              echo ":: Recovering ${BIN}.tar.gz"
              mv *.tar.gz ../../pkg/
            fi
            cd ..
          done
          cd ../pkg
          echo ""
          for BIN in *
          do
            ls -gG ${BIN}
            tigerdeep -l ${BIN} >> ../${BIN:0:20}.tiger.txt
            sha256sum ${BIN} >> ../${BIN:0:20}.sha256.txt
            sha512sum ${BIN} >> ../${BIN:0:20}.sha512.txt
          done
          mv ../*.tiger.txt .
          mv ../*.sha*.txt .
          echo ""
          echo "TIGER:"
          cat *.tiger.txt
          echo ""
          echo "SHA256:"
          cat *.sha256.txt
          echo ""
          echo "SHA512:"
          cat *.sha512.txt
          echo ""
          git tag -f nightly-build
          git push -f origin nightly-build
      - name: Nightly-build
        uses: ncipollo/release-action@v1
        with:
          prerelease: true
          allowUpdates: true
          removeArtifacts: true
          replacesArtifacts: false
          tag: nightly-build
          artifacts: pkg/*
